# Generated by Django 2.2.5 on 2022-08-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todotable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('repeat', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=500)),
            ],
        ),
    ]
